setAmbientSoundEnabled( "general", false )
setAmbientSoundEnabled( "gunfire", false )
setWorldSoundEnabled(0, 0, false)
setWorldSoundEnabled(0, 29, false)
setWorldSoundEnabled(0, 30, false)
setWorldSoundEnabled( 42, false )
setWorldSoundEnabled( 5, false )